[tool.poetry]
name = "faskapi-demo"
version = "0.1.0"
description = "testing"
authors = ["ibraheem-areeda <ibraheem.areeda@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.1"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
